language: go

sudo: required
dist: trusty
group: deprecated-2017Q2

go:
  - 1.8

services:
  - redis-server

install:
  - true

before_script:
  go get github.com/axw/gocov/gocov

script:
  gocov test ./... -v | gocov report
